### PR TITLE
add ZONESTAR printer profiles

### PR DESCRIPTION
**Pull request by ZONESTAR3D**
Hi guys,
I add ZONESTAR printer profiles, please hep to check it, thanks!

### CODE REVIEW

**Comment by supermerill** [comment]
The bed_310.stl is 66ko and the two other more than 2mo, even if it's not possible to reduce those two under 100ko, can you make them as light as possible? It's needed to not going over 100mo release archive.

same for the `bedtexture.svg`, is it to the minimum size, where every ko out is going to decrease the quality a lot?
using `<circle cx="90.5" cy="87.5" r="14 />` instead of `<path d="M 90.5,87.5 C 102.65,86.816 108.15,92.4827 107,104.5C 104.034,112.055 98.5341,114.888 90.5,113C 81.9372,108.995 79.4372,102.495 83,93.5C 85.1337,90.8474 87.6337,88.8474 90.5,87.5 Z"/>` created a better quality svg and is lighter. Also, the `opacity:0.981" fill="#fefefe` can be set only on a root node, same for the <g>.

**Comment by ZONESTAR3D** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Dear, 
        I have changed the bed stl & textrue files and pushed to github again, please check it again. thanks!
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    On 3/30/2022 ***@***.***> wrote： 



The bed_310.stl is 66ko and the two other more than 2mo, even if it's not possible to reduce those two under 100ko, can you make them as light as possible? It's needed to not going over 100mo release archive.
same for the bedtexture.svg, is it to the minimum size, where every ko out is going to decrease the quality a lot?
using <circle cx="90.5" cy="87.5" r="14 /> instead of <path d="M 90.5,87.5 C 102.65,86.816 108.15,92.4827 107,104.5C 104.034,112.055 98.5341,114.888 90.5,113C 81.9372,108.995 79.4372,102.495 83,93.5C 85.1337,90.8474 87.6337,88.8474 90.5,87.5 Z"/> created a better quality svg and is lighter. Also, the opacity:0.981" fill="#fefefe can be set only on a root node, same for the .

**Comment by ZONESTAR3D** [comment]
I have update the stl file and textrue files, please help to check, thanks!

**Comment by supermerill** [comment]
Prusa has published a version of the zonestar printers.
there is difference between their profile and the one you submit here, for example for the Z9+E4 HOTEND, they have no retract_lift, and here there is 0.5mm of retract_lift

What to choose?

**Comment by supermerill** [comment]
I've merged with prusaslicer version.
I'm using 
* the pictures your submitted here.
* the names from the prusaslicer one (to be able to merge later on)
* some prusalicer changes I found sound
* your z-lift
* I applied my `translate_from_prusa.py` script
Can you check if everything is good?

**Comment by ZONESTAR3D** [comment]
> I've merged with prusaslicer version. I'm using
> 
> * the pictures your submitted here.
> * the names from the prusaslicer one (to be able to merge later on)
> * some prusalicer changes I found sound
> * your z-lift
> * I applied my `translate_from_prusa.py` script
>   Can you check if everything is good?

Yes, I checked it and it work well, thanks! and I have upload a new version V1.0.2 today

**Comment by supermerill** [comment]
merge your last 4 commits

**Pull request closed without merging**
