### PR TITLE
Update of the VERTEX profile

### PR DESCRIPTION
**Pull request by jfestrada**
Hi, 
We need to update the profile of our printers with new  thumbnails and heatbed designs. 

These are the changes:

- Vertex Mini profile does not make sense anymore since Prusa3d has started to support 3rd party extruders
- Many bug fixes have been performed on the profile
- Thumbnail images have been updated
- New Vertex L model has been added to the profile
- New heatbed designs

### CODE REVIEW

**Comment by supermerill** [comment]
you set `elefant_foot_compensation = 0.2` but this setting doesn't exists anymore, you should write `first_layer_size_compensation = -0.2`

same for `upport_material_contact_distance`, M109 in `start_gocde` and maybe other thing i fixed previously

**Comment by supermerill** [comment]
You forgot a "and" at line 1436

**Comment by jfestrada** [comment]
Many thanks for the tips, I think that I have fixed the issues.

**Comment by supermerill** [comment]
Thanks! all seems good.
As there is a little conflict, i merged it manually.

**Pull request closed without merging**
