### PR TITLE
Added Elegoo Neptune Printers

### PR DESCRIPTION
**Pull request by mlee12382**
Profiles for Elegoo Neptune Printers tested and working in SuperSlicer 2.4.58.3

### CODE REVIEW

**Comment by supermerill** [comment]
the stl is too big.
can you decimate it to the minimum?  (just before the decimation degrade it)

**Comment by mlee12382** [comment]
> the stl is too big. can you decimate it to the minimum? (just before the decimation degrade it) ideally, ~100kio

Alternatively if it's not a requirement to have the stl I can just delete it and the references to it in the .ini?

**Comment by supermerill** [comment]
Maybe it's the best that way.
The stl has too many sueless details like the springs, some cylinders below the build plate, the wheels....
ideally all of these should be cut away, laving only the build plate and a bit of the frame around it.

**Comment by mlee12382** [comment]
Yeah, I just used the model that someone else in the Neptune community had provided, it is very "busy" and distracting when you are trying to slice something. I could probably grab a cleaner model from the printer step files but seems a little unnecessary as long as the build plate is there.

**Comment by mlee12382** [comment]
Thanks so much for all the help! :)

**Pull request merged**
